### ISSUE TITLE
only 2 cores in Calc_module_bkgd_dist (Background_Distribution_Modules)?

### ISSUE THREAD

**Issue by Oyserman** [Oyserman/ctr#35]
The number of cores is set to 2... shouldnt this be user defined in the wrapper?

**Comment by Jorisvansteenbrugge** [comment]
If the number is not provided as a functional parameter, a default of 2 is used.

The following is a line in the vignette that shows how to use a number other than 2.
```
transcriptional_responses$Run(iterations          = 100, # more would be better e.g. 10k
                              random_module_sizes = 3,  # more would be better e.g. 1:20
                              parallel_cores      = 4)
```
